# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1524"
  end

#  config.vm.synced_folder "home/", "/var/lib/jenkins", create: true
  config.vm.network "forwarded_port", guest: 8080, host: 8080
    
  config.vm.provision :shell, path: "bootstrap.sh"
end
