# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.synced_folder "/Users/AKA/Lilypond", "/Lilypond"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y lilypond
  SHELL
end
